### ISSUE TITLE
Would you add FastFlow?

### ISSUE THREAD

**Issue by mjack3** [rvorias/ind_knn_ad#26] opened 2022-04-10 11:16 UTC

**Comment by rvorias** [comment] 2022-04-10 11:23
I got a dev branch locally for it, but very difficult to reproduce. Don’t
trust the all the paperswithcode results until it is reproducible ;)

**Comment by mjack3** [comment] 2022-04-10 12:28
I'm also developing the fastflow model. I have a WIP version that gets near results (- 0.5).

It's difficult replicate because paper has incongruences and It doesn't provide implementation details.

If you wish, we can cooperate

**Comment by rvorias** [comment] 2023-07-13 10:41
Closing this for now because I don't think we'll implement FastFlow any time soon.

**Closed as completed by rvorias** 2023-07-13 10:41 UTC
